language: node_js
node_js:
- '8.9'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  yarn: true
  directories:
  - node_modules

env:
  matrix:
  - CXX=g++-4.8

  global:
    secure: S4Xccnq+tdeGUYe1gTp8ekUE6rprPAe7WDZOnBzUuqMFcqDjQWrbM++I4smnftRZ2Ua7dOm/gWqgxR6r4ND1aC/grkBq20Fnt4oaogA4gH9tdZwkfIkUX10atC9E/sg5vTpbx7wanpGJ7Qglb5NuIY8R3ewakMOGGWKLIMy+3pFLVDvn4EBatae1U59gVj9xvBUQTqIDv7Ys0gEBfSWDXbij4twtFC/NtSZn4gG3iPzi6+1eQat39V/so2lrhGn989PR04gEH3ifu1dS4DJ1VyhMf4Ya94041wHLvZP7L82ya4Gab7uD+0oLhHLpGQZgmNSl5ns8N1BDqZur1LjVvgmy25UcVvO4hhMddGbyzc7ATfaCN08ui+VDo5OivMWufLnQTWWXu4cMOdUvh6E82AsFjXcHKcVFPKDu2xGQzZJn9TPJ59JdxVvJymYY7Ig0lQ93vJgN70wFZjRb0goRQ7+32uDFX7S6+j3E2x8fhrzRDuCrS0hoRjl0qjxiQuc9ZtrgjN5OpGisfRFwQX60VZ0FHBjeA5lk8YtO6+GJDmZBadF5scJoLi5jJE1kHMYteBGb2UzXMvlrKYK+5UGc5FXSrSU2O2xaUeWu0V/TcwMH0Yw58uSHD51U93VxulI9YD2vfcZ/pOLS53dxJMmdcEH9ytMNYmGmfsfist6k+bM=

script:
- echo "Running Custom Commands"
- yarn test
- yarn code-coverage