name: Node.js Package

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}